In [2]:
import numpy as np
import pandas as pd
from feature_engine.datetime import DatetimeFeatures

In [3]:
data = pd.read_parquet(
    'd:/uber-taxi-demand/data/yellow_trip_features_v4.parquet'
)

In [5]:
data.head().T

,0,1,2,3,4
timestamp,2022-01-02 00:00:00,2022-01-02 01:00:00,2022-01-02 02:00:00,2022-01-02 03:00:00,2022-01-02 04:00:00
taxiDemand,1483,1016,703,502,357
timestamp_day_of_week,6,6,6,6,6
passengerDemand_window_7_std,1132.856188,1264.258469,1292.484006,1294.830068,1351.861486
passengerDemand_expanding_std,1926.172935,1920.277885,1941.251618,1983.175723,2029.912596
passengerDemand_lag_8,5754.0,5881.0,5875.0,5296.0,4214.0
passengerDemand_lag_24,6838.0,7738.0,5974.0,4107.0,2485.0
timestamp_year_start,0,0,0,0,0
timestamp_month_end,0,0,0,0,0
passengerDemand_lag_1,2798.0,2288.0,1594.0,1047.0,776.0
timestamp_day_of_month,2,2,2,2,2
timestamp_month_start,0,0,0,0,0
timestamp_hour,0,1,2,3,4
passengerDemand_lag_16,1233.0,1868.0,2721.0,3759.0,4633.0
passengerDemand_lag_4,4214.0,4176.0,3989.0,2798.0,2288.0
passengerDemand_lag_2,3989.0,2798.0,2288.0,1594.0,1047.0
timestamp_year_end,0,0,0,0,0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8713 entries, 0 to 8712
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   timestamp                      8713 non-null   datetime64[ns]
 1   taxiDemand                     8713 non-null   int64
 2   timestamp_day_of_week          8713 non-null   int32
 3   passengerDemand_window_7_std   8713 non-null   float64
 4   passengerDemand_expanding_std  8713 non-null   float64
 5   passengerDemand_lag_8          8713 non-null   float64
 6   passengerDemand_lag_24         8713 non-null   float64
 7   timestamp_year_start           8713 non-null   int64
 8   timestamp_month_end            8713 non-null   int64
 9   passengerDemand_lag_1          8713 non-null   float64
 10  timestamp_day_of_month         8713 non-null   int32
 11  timestamp_month_start          8713 non-null   int64
 12  timestamp_hour                 8713 non-null   int32
 13  passengerDemand_lag_16         8713 non-null   float64
 14  passengerDemand_lag_4          8713 non-null   float64
 15  passengerDemand_lag_2          8713 non-null   float64
 16  timestamp_year_end             8713 non-null   int64
dtypes: datetime64[ns](1), float64(8), int32(3), int64(5)
memory usage: 1.0 MB

In [7]:
df = data.copy()

<center><b>PCA</b></center>