# Import Necessary Libraries

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Loading data

In [3]:
data = pd.read_parquet(r"C:/Users/SRA/Desktop/backup/C/MLgrit/time_series_project/data/2022/V4_FeatureSelection_Data.parquet")
data.head()

,timestamp,taxi_demand,timestamp_quarter_end,timestamp_year_start,timestamp_leap_year,timestamp_hour,timestamp_days_in_month,passenger_demand_expanding_std,timestamp_day_of_week,taxi_demand_lag_1,...,timestamp_second,passenger_demand_lag_8,timestamp_day_of_year,timestamp_month_start,timestamp_minute,timestamp_year_end,timestamp_year,passenger_demand_lag_16,timestamp_month_end,passenger_demand_lag_1
0,2022-04-01 15:00:00,8487,0,0,0,15,30,3823.294951,4,7792.0,...,0,5653.0,91,1,0,0,2022,121.0,0,10909.0
1,2022-04-01 16:00:00,7888,0,0,0,16,30,4127.546522,4,8487.0,...,0,7085.0,91,1,0,0,2022,5046.0,0,12127.0
2,2022-04-01 17:00:00,9788,0,0,0,17,30,4301.369187,4,7888.0,...,0,7284.0,91,1,0,0,2022,3159.0,0,11245.0
3,2022-04-01 18:00:00,10527,0,0,0,18,30,4604.987587,4,9788.0,...,0,8169.0,91,1,0,0,2022,1850.0,0,13665.0
4,2022-04-01 19:00:00,9697,0,0,0,19,30,4924.257225,4,10527.0,...,0,8683.0,91,1,0,0,2022,894.0,0,14770.0

In [4]:
# sns.pairplot(data = data )

In [5]:
df = data.copy()

# Need to Standardize to Noemal/STD Normal Distribution

In [6]:
df2 = df.drop(columns=["timestamp"])
mean = np.mean(df2)
mean

1127.1078971668942

In [7]:
std_dev = np.std(df2)
std_dev

C:\Users\SRA\Desktop\backup\C\MLgrit\time_series_project\timeseriesENV\lib\site-packages\numpy\core\fromnumeric.py:3643: FutureWarning: The behavior of DataFrame.std with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)

taxi_demand                       2879.949842
timestamp_quarter_end                0.085390
timestamp_year_start                 0.052411
timestamp_leap_year                  0.000000
timestamp_hour                       6.922886
timestamp_days_in_month              0.842100
passenger_demand_expanding_std     148.428710
timestamp_day_of_week                2.002322
taxi_demand_lag_1                 2879.985085
timestamp_day_of_month               8.749852
timestamp_second                     0.000000
passenger_demand_lag_8            4051.795459
timestamp_day_of_year              105.123223
timestamp_month_start                0.174215
timestamp_minute                     0.000000
timestamp_year_end                   0.010713
timestamp_year                       0.000000
passenger_demand_lag_16           4051.638253
timestamp_month_end                  0.168873
passenger_demand_lag_1            4052.207437
dtype: float64

In [8]:
df2.head()

,taxi_demand,timestamp_quarter_end,timestamp_year_start,timestamp_leap_year,timestamp_hour,timestamp_days_in_month,passenger_demand_expanding_std,timestamp_day_of_week,taxi_demand_lag_1,timestamp_day_of_month,timestamp_second,passenger_demand_lag_8,timestamp_day_of_year,timestamp_month_start,timestamp_minute,timestamp_year_end,timestamp_year,passenger_demand_lag_16,timestamp_month_end,passenger_demand_lag_1
0,8487,0,0,0,15,30,3823.294951,4,7792.0,1,0,5653.0,91,1,0,0,2022,121.0,0,10909.0
1,7888,0,0,0,16,30,4127.546522,4,8487.0,1,0,7085.0,91,1,0,0,2022,5046.0,0,12127.0
2,9788,0,0,0,17,30,4301.369187,4,7888.0,1,0,7284.0,91,1,0,0,2022,3159.0,0,11245.0
3,10527,0,0,0,18,30,4604.987587,4,9788.0,1,0,8169.0,91,1,0,0,2022,1850.0,0,13665.0
4,9697,0,0,0,19,30,4924.257225,4,10527.0,1,0,8683.0,91,1,0,0,2022,894.0,0,14770.0

In [9]:
# standardized_scores = [(x - mean) / std_dev for x in df2]
# z = (x - u) / s

In [10]:
# StandardScaler?

In [11]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [25]:
scaler = StandardScaler()
scaler.fit(df2.drop(columns='taxi_demand'))

StandardScaler()

In [26]:
df2.loc[:, df2.columns[:-1]] = scaler.transform(df2.drop(columns='taxi_demand'))
df2.head()

,taxi_demand,timestamp_quarter_end,timestamp_year_start,timestamp_leap_year,timestamp_hour,timestamp_days_in_month,passenger_demand_expanding_std,timestamp_day_of_week,taxi_demand_lag_1,timestamp_day_of_month,timestamp_second,passenger_demand_lag_8,timestamp_day_of_year,timestamp_month_start,timestamp_minute,timestamp_year_end,timestamp_year,passenger_demand_lag_16,timestamp_month_end,passenger_demand_lag_1
0,-0.052556,0.0,0.505760,-0.522269,-1.208005,0.500165,1.794973,-1.67886,0.0,0.487895,-0.873014,5.560193,0.0,-0.010714,0.0,-0.877515,-0.173985,1.784811,1.784811,10909.0
1,-0.052556,0.0,0.650209,-0.522269,0.841812,0.500165,2.036293,-1.67886,0.0,0.841318,-0.873014,5.560193,0.0,-0.010714,0.0,0.338043,-0.173985,2.085388,2.085388,12127.0
2,-0.052556,0.0,0.794657,-0.522269,2.012897,0.500165,1.828306,-1.67886,0.0,0.890432,-0.873014,5.560193,0.0,-0.010714,0.0,-0.127694,-0.173985,1.867729,1.867729,11245.0
3,-0.052556,0.0,0.939105,-0.522269,4.058447,0.500165,2.488032,-1.67886,0.0,1.108854,-0.873014,5.560193,0.0,-0.010714,0.0,-0.450774,-0.173985,2.464934,2.464934,13665.0
4,-0.052556,0.0,1.083554,-0.522269,6.209444,0.500165,2.744630,-1.67886,0.0,1.235711,-0.873014,5.560193,0.0,-0.010714,0.0,-0.686728,-0.173985,2.737625,2.737625,14770.0

In [12]:
# sns.pairplot(data = df2)

In [13]:
scaler.mean_

array([7.34534603e-03, 2.75450476e-03, 0.00000000e+00, 1.14986801e+01,
       3.04398026e+01, 4.00259752e+03, 2.99850798e+00, 2.62250522e+03,
       1.56897739e+01, 0.00000000e+00, 3.67614989e+03, 1.82774016e+02,
       3.13324917e-02, 0.00000000e+00, 1.14771032e-04, 2.02200000e+03,
       3.67637186e+03, 2.93813841e-02, 3.67657649e+03])

In [14]:
scaler

StandardScaler()

In [39]:
# Lets save our Train data

In [15]:
df2.to_parquet(r"C:/Users/SRA/Desktop/backup/C/MLgrit/time_series_project/data/2022/V5_NormalizeScaling_trainData.parquet", index=False)